openapi: 3.0.0
info:
  title: Invalid API
  version: 1.0.0

paths:
  /test:
    get:
      responses:
        '200'  # Invalid YAML - missing colon
          description: Test
    post
      # Missing colon here too
      responses:
        200:
          description: Invalid
